<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>

        <PackAsTool>true</PackAsTool>
        <ToolCommandName>nott</ToolCommandName>
        <PackageId>Nott.CLI</PackageId>
        
        <Title>Nott</Title>
        <Description>An AI Assistant living in your terminal.</Description>
        <RepositoryUrl>https://github.com/laomobk/nott</RepositoryUrl>
        <RepositoryType>Github</RepositoryType>
        <PackageTags>Agent</PackageTags>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Newtonsoft.Json" Version="13.0.5-beta1" />
      <PackageReference Include="ReadLine" Version="2.0.1" />
      <PackageReference Include="Spectre.Console" Version="0.57.3-alpha.0.7" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Nott.Agent\Nott.Agent.csproj" />
    </ItemGroup>

</Project>
